"""
OraVisionAI — YOLO Detection Model

Stores structured spatial lesion bounding box detections generated by the YOLO model.
"""

from __future__ import annotations

import datetime
import decimal
import uuid
from typing import TYPE_CHECKING, Any, Dict, Optional

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, Numeric, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.ai_model import AIModel
    from app.models.screening import Screening
    from app.models.screening_image import ScreeningImage


class YOLODetection(Base):
    """Bounding box detection finding for oral lesions and conditions."""

    __tablename__ = "yolo_detections"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    screening_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("screenings.id", ondelete="CASCADE"),
        nullable=False,
    )
    screening_image_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("screening_images.id", ondelete="CASCADE"),
        nullable=False,
    )
    ai_model_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("ai_models.id", ondelete="RESTRICT"),
        nullable=False,
    )
    detected_class: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    confidence: Mapped[decimal.Decimal] = mapped_column(
        Numeric(5, 4),
        nullable=False,
    )
    bbox_x_min: Mapped[decimal.Decimal] = mapped_column(
        Numeric(7, 4),
        nullable=False,
    )
    bbox_y_min: Mapped[decimal.Decimal] = mapped_column(
        Numeric(7, 4),
        nullable=False,
    )
    bbox_x_max: Mapped[decimal.Decimal] = mapped_column(
        Numeric(7, 4),
        nullable=False,
    )
    bbox_y_max: Mapped[decimal.Decimal] = mapped_column(
        Numeric(7, 4),
        nullable=False,
    )
    detection_metadata: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSONB,
        nullable=True,
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    __table_args__ = (
        CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name="chk_yolo_confidence",
        ),
        CheckConstraint(
            "bbox_x_min >= 0.0 AND bbox_x_min <= 1.0",
            name="chk_bbox_x_min",
        ),
        CheckConstraint(
            "bbox_y_min >= 0.0 AND bbox_y_min <= 1.0",
            name="chk_bbox_y_min",
        ),
        CheckConstraint(
            "bbox_x_max >= 0.0 AND bbox_x_max <= 1.0",
            name="chk_bbox_x_max",
        ),
        CheckConstraint(
            "bbox_y_max >= 0.0 AND bbox_y_max <= 1.0",
            name="chk_bbox_y_max",
        ),
        Index("idx_yolo_screening_id", "screening_id"),
        Index("idx_yolo_image_id", "screening_image_id"),
    )

    # Relationships
    screening: Mapped[Screening] = relationship(
        "Screening",
        back_populates="yolo_detections",
    )
    screening_image: Mapped[ScreeningImage] = relationship(
        "ScreeningImage",
        back_populates="yolo_detections",
    )
    ai_model: Mapped[AIModel] = relationship(
        "AIModel",
        back_populates="detections",
    )

