import { auth } from '../config/firebase';
import { apiBaseUrl } from '../config/environment';
import { HttpClient } from './http';
import type {
  UserResponse, ConsultationResponse, ConsultationListResponse, Appointment, AppointmentListResponse,
  ScreeningResponse, ScreeningListResponse, ScreeningDetailResponse, ScreeningReviewResponse,
  ScreeningInferenceResponse, ScreeningImageResponse, ReportResponse, DentistProfile,
  DentistAvailabilityListResponse, DentistPendingReviewListResponse, DentistPatientCaseListResponse,
  DentistAssessment, DentistAssessmentCreate, ConversationResponse, ConversationListResponse,
  MessageListResponse, MessageResponse, NotificationListResponse, StreamTokenResponse, AttachmentUrlResponse, ShareableReportItem,
  ScreeningWorkflow,
} from '../types';

export const http = new HttpClient(apiBaseUrl, async (refresh) => auth.currentUser ? auth.currentUser.getIdToken(refresh) : null);
const id = encodeURIComponent;

export const api = {
  me: () => http.get<UserResponse>('/api/users/me'),
  register: (role: 'patient' | 'dentist', first_name: string, last_name: string) => http.post<UserResponse>('/api/users/sync', { role, first_name, last_name }),
  consultations: (signal?: AbortSignal) => http.get<ConsultationListResponse>('/api/consultations', signal),
  consultation: (value: string, signal?: AbortSignal) => http.get<ConsultationResponse>(`/api/consultations/${id(value)}`, signal),
  streamToken: (value: string) => http.post<StreamTokenResponse>(`/api/consultations/${id(value)}/stream-token`, {}),
  createConsultation: (appointment: string, consultation_type: 'video' | 'audio' | 'chat' = 'video') => http.post<ConsultationResponse>(`/api/appointments/${id(appointment)}/consultation`, { consultation_type }),
  appointmentConsultation: (appointment: string) => http.get<ConsultationResponse>(`/api/appointments/${id(appointment)}/consultation`),
  startConsultation: (value: string) => http.patch<ConsultationResponse>(`/api/consultations/${id(value)}/start`, {}),
  endConsultation: (value: string, clinical_summary?: string) => http.patch<ConsultationResponse>(`/api/consultations/${id(value)}/end`, { clinical_summary: clinical_summary || null }),
  failConsultation: (value: string) => http.patch<ConsultationResponse>(`/api/consultations/${id(value)}/fail`, {}),
  appointments: () => http.get<AppointmentListResponse>('/api/appointments'),
  appointment: (value: string) => http.get<Appointment>(`/api/appointments/${id(value)}`),
  confirmAppointment: (value: string) => http.post<Appointment>(`/api/appointments/${id(value)}/confirm`),
  cancelAppointment: (value: string, cancellation_reason: string) => http.patch<Appointment>(`/api/appointments/${id(value)}/cancel`, { cancellation_reason }),
  rejectAppointment: (value: string, cancellation_reason: string) => http.post<Appointment>(`/api/appointments/${id(value)}/reject`, { cancellation_reason }),
  screenings: () => http.get<ScreeningListResponse>('/api/screenings?page=1&page_size=50'),
  createScreening: (clinical_notes: string) => http.post<ScreeningResponse>('/api/screenings', { clinical_notes: clinical_notes || null }),
  startScreeningWorkflow: (value: string, body: FormData, signal: AbortSignal) => http.request<ScreeningWorkflow>(`/api/screenings/${id(value)}/workflow`, 'POST', { body, signal, timeoutMs: 120000 }),
  screeningWorkflow: (value: string, signal: AbortSignal) => http.get<ScreeningWorkflow>(`/api/screenings/${id(value)}/workflow`, signal),
  cancelScreeningWorkflow: (value: string) => http.post<ScreeningWorkflow>(`/api/screenings/${id(value)}/workflow/cancel`),
  screening: (value: string) => http.get<ScreeningDetailResponse>(`/api/screenings/${id(value)}`),
  screeningReview: (value: string) => http.get<ScreeningReviewResponse>(`/api/screenings/${id(value)}/review`),
  uploadImage: (value: string, body: FormData) => http.post<ScreeningImageResponse>(`/api/screenings/${id(value)}/images`, body, 120000),
  runAI: (value: string) => http.post<ScreeningInferenceResponse>(`/api/screenings/${id(value)}/run-ai`, {}, 300000),
  generateExplanation: (value: string) => http.post(`/api/screenings/${id(value)}/xai`, { include_secondary: false, force_recompute: false }, 300000),
  generateRisk: (value: string) => http.post(`/api/screenings/${id(value)}/risk-assessment`, { force_recompute: false }, 120000),
  signedArtifact: (value: string, path: string, signal?: AbortSignal) => http.get<{ signed_url: string }>(`/api/screenings/${id(value)}/artifacts/signed-url?path=${encodeURIComponent(path)}`, signal),
  report: (value: string) => http.post<ReportResponse>(`/api/screenings/${id(value)}/report`, { force_regenerate: false, report_title: 'Oral Health AI Screening Report' }, 120000),
  requestReview: (value: string, dentist_id: string) => http.post(`/api/screenings/${id(value)}/request-review`, { dentist_id, patient_notes: null }),
  dentists: () => http.get<DentistProfile[]>('/api/dentists'),
  dentistProfile: () => http.get<DentistProfile>('/api/dentists/me'),
  updateDentistProfile: (body: { bio?: string; clinic_name?: string; specialization?: string }) => http.patch<DentistProfile>('/api/dentists/me', body),
  availability: (value: string) => http.get<DentistAvailabilityListResponse>(`/api/dentists/${id(value)}/availability`),
  bookAppointment: (value: string, body: { scheduled_start: string; scheduled_end: string; appointment_type: string; patient_notes: string | null }) => http.post<Appointment>(`/api/dentists/${id(value)}/appointments`, body),
  pendingReviews: () => http.get<DentistPendingReviewListResponse>('/api/dentists/me/reviews'),
  patientCases: () => http.get<DentistPatientCaseListResponse>('/api/dentists/me/patient-cases'),
  assessment: (value: string) => http.get<DentistAssessment>(`/api/screenings/${id(value)}/assessment`),
  saveAssessment: (value: string, body: DentistAssessmentCreate, exists: boolean) => exists ? http.patch<DentistAssessment>(`/api/screenings/${id(value)}/assessment`, body) : http.post<DentistAssessment>(`/api/screenings/${id(value)}/assessment`, body),
  conversations: () => http.get<ConversationListResponse>('/api/conversations'),
  conversation: (value: string) => http.get<ConversationResponse>(`/api/conversations/${id(value)}`),
  startConversation: (target: string, role: 'patient' | 'dentist') => http.post<ConversationResponse>(`/api/${role === 'patient' ? 'dentists' : 'patients'}/${id(target)}/conversations`),
  messages: (value: string, offset = 0, signal?: AbortSignal) => http.get<MessageListResponse>(`/api/conversations/${id(value)}/messages?limit=100&offset=${offset}`, signal),
  sendMessage: (value: string, content: string) => http.post<MessageResponse>(`/api/conversations/${id(value)}/messages`, { content, message_type: 'text' }),
  messageAttachment: (value: string) => http.get<AttachmentUrlResponse>(`/api/messages/attachments/${id(value)}/url`),
  uploadMessage: (value: string, body: FormData) => http.post<MessageResponse>(`/api/conversations/${id(value)}/messages/upload`, body, 120000),
  shareableReports: (value: string) => http.get<ShareableReportItem[]>(`/api/conversations/${id(value)}/shareable-reports`),
  shareReport: (value: string, report_id: string) => http.post<MessageResponse>(`/api/conversations/${id(value)}/share-report`, { report_id }),
  submitVerification: (body: { document_type: string; document_url: string; file_name: string }) => http.post('/api/dentists/me/verification', body),
  myAvailability: () => http.get<DentistAvailabilityListResponse>('/api/dentists/me/availability'),
  addAvailability: (body: { day_of_week: number; start_time: string; end_time: string; slot_duration_minutes: number; is_active: boolean }) => http.post('/api/dentists/me/availability', body),
  setAvailability: (value: string, is_active: boolean) => http.patch(`/api/dentists/me/availability/${id(value)}`, { is_active }),
  readMessages: (value: string) => http.patch(`/api/conversations/${id(value)}/read`),
  notifications: () => http.get<NotificationListResponse>('/api/notifications?limit=50'),
  readNotification: (value: string) => http.patch(`/api/notifications/${id(value)}/read`),
};
