import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { api } from '../../api';
import { useResource } from '../../hooks/useResource';
import { Button, Card, Empty, Field, Notice, ResourceState, Screen, StatusPill } from '../../components/ui';
import { colors, styles } from '../../theme';
import { availableSlots } from '../../utils/availability';
import { messageOf } from '../../utils/consultation';
export default function Dentist() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const r = useResource(async () => { const [directory, windows] = await Promise.all([api.dentists(), api.availability(id)]); const dentist = directory.find((d) => d.id === id); if (!dentist) throw new Error('This practitioner is not available.'); return { dentist, windows: windows.items }; });
  const [date, setDate] = useState(new Date().toISOString().slice(0,10)); const [selected, setSelected] = useState(''); const [type, setType] = useState('video_teleconsultation'); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const slots = availableSlots(r.data?.windows || [], date); const d = r.data?.dentist;
  async function book() { if (busy) return; setBusy(true); setError(''); setSuccess(''); try { const slot = slots.find((s) => s.start === selected); if (!slot) throw new Error('Choose an available future time.'); await api.bookAppointment(id, { scheduled_start: slot.start, scheduled_end: slot.end, appointment_type: type, patient_notes: notes.trim() || null }); setSelected(''); setSuccess('Your appointment request has been sent. Your practitioner will confirm it.'); } catch(e) { setError(messageOf(e)); } finally { setBusy(false); } }
  async function message() { setBusy(true); setError(''); try { const c = await api.startConversation(id, 'patient'); router.push({ pathname: '/conversation/[id]', params: { id: c.id } }); } catch(e) { setError(messageOf(e)); } finally { setBusy(false); } }
  return <Screen><ResourceState {...r} retry={() => void r.refresh()} />{d && <><Card><StatusPill status="verified" /><Text style={styles.title}>Dr. {d.first_name} {d.last_name}</Text><Text style={styles.body}>{d.specialization} · {d.clinic_name}</Text>{!!(d.bio) && <Text style={styles.body}>{d.bio}</Text>}<Button label="Send a message" variant="outline" disabled={busy} onPress={() => void message()} /></Card><Text style={styles.heading}>Choose a time</Text><Text style={styles.caption}>Availability dates use UTC. Each time below is shown in your device timezone. The server checks conflicts before accepting a request.</Text><Field label="Availability date (YYYY-MM-DD, UTC)" value={date} onChangeText={(v) => { setDate(v); setSelected(''); }} autoCapitalize="none" maxLength={10} /><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{slots.map((s) => <Pressable key={s.start} accessibilityRole="radio" accessibilityState={{ selected: selected === s.start }} onPress={() => setSelected(s.start)} style={{ padding: 13, borderRadius: 8, backgroundColor: selected === s.start ? colors.teal : colors.white, borderWidth: 1, borderColor: colors.line }}><Text style={{ color: selected === s.start ? colors.white : colors.ink }}>{new Date(s.start).toLocaleString(undefined, { month:'short',day:'numeric',hour:'2-digit',minute:'2-digit' })}</Text></Pressable>)}</View>{slots.length === 0 && <Empty title="No slots on this date" message="Choose a different date to see published availability." icon="calendar" />}<View style={styles.row}>{['video_teleconsultation','audio_teleconsultation','in_person_consultation'].map((t) => <Button key={t} label={t.split('_')[0]} variant={type === t ? 'primary' : 'outline'} style={{ flex:1, paddingHorizontal:8 }} onPress={() => setType(t)} />)}</View><Field label="Notes for your practitioner (optional)" multiline maxLength={2000} value={notes} onChangeText={setNotes} />{!!(error) && <Notice error message={error} />}{!!(success) && <><Notice message={success} /><Button label="View appointments" variant="outline" onPress={() => router.push('/appointments')} /></>}<Button label="Request appointment" disabled={!selected} loading={busy} onPress={() => void book()} /></>}</Screen>;
}
