import { useEffect, useState } from 'react';
import { Image, Linking, Switch, Text, View } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { api } from '../../api';
import { useSession } from '../../context/Session';
import { useResource } from '../../hooks/useResource';
import { Button, Card, Field, Notice, ResourceState, Screen, StatusPill } from '../../components/ui';
import { colors, styles } from '../../theme';
import { messageOf } from '../../utils/consultation';
import type { DentistProfile } from '../../types';

export default function ScreeningDetails() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { profile } = useSession(); const doctor = profile?.role === 'dentist';
  const r = useResource(() => api.screeningReview(id)); const review = r.data;
  const [artifacts, setArtifacts] = useState<{ name: string; url: string }[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState('');
  const [dentists, setDentists] = useState<DentistProfile[]>([]); const [dentistId, setDentistId] = useState(''); const [observations, setObservations] = useState<string | null>(null); const [diagnosis, setDiagnosis] = useState<string | null>(null); const [treatment, setTreatment] = useState<string | null>(null); const [referral, setReferral] = useState<boolean | null>(null); const [specialty, setSpecialty] = useState<string | null>(null);
  const own = review?.dentist_assessments.find((a) => a.dentist_id && doctor && a.dentist_id === dentistId);
  useEffect(() => { let alive = true; (doctor ? api.dentistProfile().then((d) => { if (alive) setDentistId(d.id); }) : api.dentists().then((d) => { if (alive) setDentists(d.filter((v) => v.verification_status === 'approved')); })).catch((e) => { if (alive) setError(messageOf(e)); }); return () => { alive = false; }; }, [doctor]);
  useEffect(() => {
    if (!review) return; let alive = true;
    const paths = review.images.map((i,n) => ({ name: `Oral image ${n+1}`, path: i.storage_path }));
    const xai = review.xai_results.find((a) => a.is_primary_user_facing); if (xai) paths.push({ name: `${xai.method} explanation`, path: xai.overlay_image_storage_path });
    Promise.allSettled(paths.map(async (a) => ({ name: a.name, url: (await api.signedArtifact(id,a.path)).signed_url }))).then((results) => { if (!alive) return; setArtifacts(results.flatMap((v) => v.status === 'fulfilled' ? [v.value] : [])); if (results.some((v) => v.status === 'rejected')) setError('Some images could not be loaded. Refresh to try again.'); });
    return () => { alive = false; };
  }, [review, id]);
  const values = { observations: observations ?? own?.clinical_observations ?? '', diagnosis: diagnosis ?? own?.diagnosis_notes ?? '', treatment: treatment ?? own?.treatment_recommendation ?? '', referral: referral ?? own?.referral_needed ?? false, specialty: specialty ?? own?.referral_specialty ?? '' };
  async function perform(action: 'report' | 'review' | 'save' | 'finalize' | 'explain' | 'risk') {
    if (busy) return; setBusy(true); setError(''); setSuccess('');
    try {
      if (action === 'report') { const report = await api.report(id); if (!report.pdf_storage_path) throw new Error('The report PDF is not available yet.'); const signed = await api.signedArtifact(id,report.pdf_storage_path); await Linking.openURL(signed.signed_url); }
      else if (action === 'explain' || action === 'risk') { if (action === 'explain') await api.generateExplanation(id); else await api.generateRisk(id); await r.refresh(true); setSuccess(action === 'explain' ? 'Your visual explanation is ready.' : 'Your next-step guidance is ready.'); }
      else if (action === 'review') { if (!dentistId) throw new Error('Choose a practitioner to request review.'); await api.requestReview(id,dentistId); setSuccess('Your review request has been sent.'); await r.refresh(true); }
      else { if (!values.observations.trim() || !values.diagnosis.trim() || !values.treatment.trim()) throw new Error('Complete the observations, diagnosis and treatment fields.'); if (values.referral && !values.specialty.trim()) throw new Error('Enter the referral specialty.'); await api.saveAssessment(id, { clinical_observations:values.observations.trim(),diagnosis_notes:values.diagnosis.trim(),treatment_recommendation:values.treatment.trim(), referral_needed:values.referral,referral_specialty:values.referral ? values.specialty.trim() : null,is_finalized: action === 'finalize' }, !!own); setSuccess(action === 'finalize' ? 'Assessment finalized and locked.' : 'Assessment draft saved.'); await r.refresh(true); }
    } catch(e) { setError(messageOf(e)); } finally { setBusy(false); }
  }
  return <Screen refreshing={r.loading} onRefresh={() => void r.refresh()}><ResourceState {...r} retry={() => void r.refresh()} />{!!(error) && <Notice error message={error} />}{!!(success) && <Notice message={success} />}{review && <><View style={styles.row}><Text style={[styles.title,{flex:1}]}>Screening overview</Text><StatusPill status={review.screening_status} /></View><Text style={styles.body}>{review.patient_name} · {new Date(review.screening_created_at).toLocaleDateString()}</Text>{!!(review.patient_notes) && <Card><Text style={styles.heading}>Patient notes</Text><Text style={styles.body}>{review.patient_notes}</Text></Card>}{artifacts.map((a) => <Card key={a.name}><Text style={styles.heading}>{a.name}</Text><Image source={{ uri:a.url }} resizeMode="contain" accessibilityLabel={a.name} style={{height:230,width:'100%',borderRadius:12}} /></Card>)}
    {review.primary_prediction && <Card><Text style={styles.kicker}>AI SCREENING FINDINGS</Text><Text style={styles.heading}>{review.primary_prediction.predicted_class}</Text><Text style={styles.caption}>Model confidence: {(review.primary_prediction.confidence * 100).toFixed(1)}%. This is a model score, not a disease probability.</Text>{review.primary_prediction.probabilities.map((p) => <View key={p.class_code} style={{gap:6}}><View style={styles.between}><Text style={styles.caption}>{p.class_name}</Text><Text style={styles.caption}>{(p.probability*100).toFixed(1)}%</Text></View><View style={{height:5,backgroundColor:colors.mint,borderRadius:3}}><View style={{height:5,width:`${Math.max(0,Math.min(100,p.probability*100))}%`,backgroundColor:colors.teal,borderRadius:3}} /></View></View>)}</Card>}
    {review.risk_assessment && <Card><Text style={styles.heading}>Recommended next step</Text><StatusPill status={review.risk_assessment.risk_level} /><Text style={styles.body}>{review.risk_assessment.summary}</Text><Text style={styles.body}>{review.risk_assessment.recommended_action}</Text></Card>}
    <Notice message="Automated screening supports professional review. Consult a licensed practitioner for a clinical diagnosis." />
    {review.primary_prediction && review.xai_results.length === 0 && <Button label="Generate visual explanation" variant="outline" loading={busy} onPress={() => void perform('explain')} />}
    {review.primary_prediction && !review.risk_assessment && <Button label="Generate next-step guidance" variant="outline" loading={busy} onPress={() => void perform('risk')} />}
    {review.dentist_assessments.map((a) => <Card key={a.id}><Text style={styles.kicker}>PROFESSIONAL ASSESSMENT</Text><Text style={styles.heading}>{a.dentist_name || 'Assigned practitioner'}</Text><StatusPill status={a.is_finalized ? 'finalized' : 'draft'} /><Text style={styles.body}>{a.clinical_observations}</Text><Text style={styles.body}>{a.diagnosis_notes}</Text><Text style={styles.body}>{a.treatment_recommendation}</Text>{a.referral_needed && <Text style={styles.body}>Referral: {a.referral_specialty || 'Specialist review'}</Text>}</Card>)}
    {doctor && !own?.is_finalized && <Card><Text style={styles.heading}>Your clinical review</Text><Field label="Clinical observations" multiline value={values.observations} onChangeText={setObservations} editable={!busy} /><Field label="Diagnosis notes" multiline value={values.diagnosis} onChangeText={setDiagnosis} editable={!busy} /><Field label="Treatment recommendation" multiline value={values.treatment} onChangeText={setTreatment} editable={!busy} /><View style={styles.between}><Text style={styles.body}>Referral needed</Text><Switch accessibilityLabel="Referral needed" value={values.referral} onValueChange={setReferral} disabled={busy} trackColor={{true:colors.teal}} /></View>{values.referral && <Field label="Referral specialty" value={values.specialty} onChangeText={setSpecialty} maxLength={150} />}<Button label="Save assessment draft" loading={busy} onPress={() => void perform('save')} /><Notice message="Finalizing permanently locks this assessment. Review your notes before continuing." /><Button label="Finalize assessment" variant="outline" disabled={busy} onPress={() => void perform('finalize')} /></Card>}
    {!doctor && review.primary_prediction && <Card><Text style={styles.heading}>Ask for professional review</Text>{dentists.map((d) => <Button key={d.id} label={`Dr. ${d.first_name} ${d.last_name}${dentistId === d.id ? ' ✓' : ''}`} variant="outline" disabled={busy} onPress={() => setDentistId(d.id)} />)}{dentists.length === 0 && <Text style={styles.body}>No verified practitioners are available yet.</Text>}<Button label="Request review" loading={busy} disabled={!dentistId} onPress={() => void perform('review')} /></Card>}
    {review.primary_prediction && <Button label="View PDF report" icon="file-text" variant="outline" loading={busy} onPress={() => void perform('report')} />}</>}</Screen>;
}
