"""initial_database_schema

Revision ID: 001_initial_database_schema
Revises: None
Create Date: 2026-09-01 21:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial_database_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('architecture', sa.String(length=100), nullable=False),
    sa.Column('weights_path', sa.Text(), nullable=True),
    sa.Column('input_shape', sa.String(length=50), nullable=False),
    sa.Column('class_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_layers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("model_type IN ('classifier', 'detector', 'multimodal', 'risk_engine')", name='chk_models_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    op.create_index('idx_ai_models_active', 'ai_models', ['model_type', 'is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('patient', 'dentist', 'admin')", name='chk_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_firebase_uid', 'users', ['firebase_uid'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user_id', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('dentists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=150), nullable=False),
    sa.Column('clinic_name', sa.String(length=200), nullable=True),
    sa.Column('clinic_address', sa.Text(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verification_status IN ('pending', 'approved', 'rejected', 'suspended')", name='chk_dentists_verification_status'),
    sa.CheckConstraint('years_of_experience >= 0', name='chk_dentists_experience'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_dentists_user_id', 'dentists', ['user_id'], unique=True)
    op.create_index('idx_dentists_verification_status', 'dentists', ['verification_status'], unique=False)
    op.create_index('idx_dentists_license', 'dentists', ['license_number'], unique=True)
    op.create_index(op.f('ix_dentists_verification_status'), 'dentists', ['verification_status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("notification_type IN ('screening_completed', 'screening_failed', 'appointment_booked', 'appointment_confirmed', 'appointment_cancelled', 'dentist_verified', 'dentist_assessment_added', 'new_message', 'system_alert')", name='chk_notification_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('male', 'female', 'other', 'prefer_not_to_say')", name='chk_patients_gender'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_patients_user_id', 'patients', ['user_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('dentist_id', sa.UUID(), nullable=False),
    sa.Column('stream_channel_id', sa.String(length=128), nullable=False),
    sa.Column('conversation_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("conversation_type IN ('direct', 'consultation_chat')", name='chk_conversation_type'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'dentist_id', 'conversation_type', name='uq_patient_dentist_conv'),
    sa.UniqueConstraint('stream_channel_id')
    )
    op.create_index('idx_conv_patient', 'conversations', ['patient_id'], unique=False)
    op.create_index('idx_conv_stream_channel', 'conversations', ['stream_channel_id'], unique=True)
    op.create_index('idx_conv_dentist', 'conversations', ['dentist_id'], unique=False)
    op.create_table('dentist_availabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dentist_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='chk_day_of_week'),
    sa.CheckConstraint('end_time > start_time', name='chk_time_window'),
    sa.CheckConstraint('slot_duration_minutes > 0', name='chk_slot_duration'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_availability_dentist', 'dentist_availabilities', ['dentist_id', 'day_of_week', 'is_active'], unique=False)
    op.create_table('dentist_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dentist_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='chk_verification_status'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dentist_verifications_status', 'dentist_verifications', ['status'], unique=False)
    op.create_index('idx_dentist_verifications_dentist_id', 'dentist_verifications', ['dentist_id'], unique=False)
    op.create_index(op.f('ix_dentist_verifications_status'), 'dentist_verifications', ['status'], unique=False)
    op.create_table('patient_dentist_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('dentist_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('established_via', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("established_via IN ('appointment', 'direct_invite', 'screening_share')", name='chk_pdr_established_via'),
    sa.CheckConstraint("status IN ('active', 'pending_consent', 'revoked', 'archived')", name='chk_pdr_status'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'dentist_id', name='uq_patient_dentist')
    )
    op.create_index(op.f('ix_patient_dentist_relationships_status'), 'patient_dentist_relationships', ['status'], unique=False)
    op.create_index('idx_pdr_patient_id', 'patient_dentist_relationships', ['patient_id'], unique=False)
    op.create_index('idx_pdr_status', 'patient_dentist_relationships', ['status'], unique=False)
    op.create_index('idx_pdr_dentist_id', 'patient_dentist_relationships', ['dentist_id'], unique=False)
    op.create_table('patient_medical_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medical_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dental_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_medications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('smoking_status', sa.String(length=50), nullable=True),
    sa.Column('alcohol_consumption', sa.String(length=50), nullable=True),
    sa.Column('betel_quid_user', sa.Boolean(), nullable=False),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("alcohol_consumption IN ('none', 'occasional', 'moderate', 'frequent')", name='chk_medical_alcohol_consumption'),
    sa.CheckConstraint("smoking_status IN ('never', 'former', 'occasional', 'regular', 'heavy')", name='chk_medical_smoking_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index('idx_medical_profiles_patient_id', 'patient_medical_profiles', ['patient_id'], unique=True)
    op.create_table('screenings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'uploading', 'processing', 'completed', 'failed')", name='chk_screenings_status'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_screenings_patient_id', 'screenings', ['patient_id'], unique=False)
    op.create_index('idx_screenings_status', 'screenings', ['status'], unique=False)
    op.create_index('idx_screenings_active', 'screenings', ['patient_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index(op.f('ix_screenings_status'), 'screenings', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('dentist_id', sa.UUID(), nullable=False),
    sa.Column('screening_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by_id', sa.UUID(), nullable=True),
    sa.Column('patient_notes', sa.Text(), nullable=True),
    sa.Column('dentist_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("appointment_type IN ('video_teleconsultation', 'audio_teleconsultation', 'in_person_consultation', 'follow_up')", name='chk_appt_type'),
    sa.CheckConstraint("status IN ('requested', 'confirmed', 'in_progress', 'completed', 'cancelled', 'rescheduled', 'no_show')", name='chk_appt_status'),
    sa.CheckConstraint('scheduled_end > scheduled_start', name='chk_appt_time'),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentists.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index('idx_appts_dentist', 'appointments', ['dentist_id', 'scheduled_start'], unique=False)
    op.create_index('idx_appts_status', 'appointments', ['status'], unique=False)
    op.create_index('idx_appts_patient', 'appointments', ['patient_id', 'scheduled_start'], unique=False)
    op.create_table('dentist_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screening_id', sa.UUID(), nullable=False),
    sa.Column('dentist_id', sa.UUID(), nullable=False),
    sa.Column('clinical_observations', sa.Text(), nullable=False),
    sa.Column('diagnosis_notes', sa.Text(), nullable=False),
    sa.Column('treatment_recommendation', sa.Text(), nullable=False),
    sa.Column('referral_needed', sa.Boolean(), nullable=False),
    sa.Column('referral_specialty', sa.String(length=150), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentists.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dentist_assessments_dentist', 'dentist_assessments', ['dentist_id'], unique=False)
    op.create_index('idx_dentist_assessments_screening', 'dentist_assessments', ['screening_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('stream_message_id', sa.String(length=128), nullable=True),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_storage_path', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("message_type IN ('text', 'image', 'screening_share', 'system')", name='chk_message_type'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screening_id', sa.UUID(), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('generated_by_id', sa.UUID(), nullable=True),
    sa.Column('report_title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_storage_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_number'),
    sa.UniqueConstraint('screening_id')
    )
    op.create_index('idx_reports_screening_id', 'reports', ['screening_id'], unique=True)
    op.create_index('idx_reports_number', 'reports', ['report_number'], unique=True)
    op.create_table('screening_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screening_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('image_sha256', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_screening_images_screening_id', 'screening_images', ['screening_id'], unique=False)
    op.create_table('ai_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screening_id', sa.UUID(), nullable=False),
    sa.Column('screening_image_id', sa.UUID(), nullable=False),
    sa.Column('ai_model_id', sa.UUID(), nullable=False),
    sa.Column('predicted_class', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('inference_duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('processing', 'completed', 'failed')", name='chk_prediction_status'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='chk_prediction_confidence'),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screening_image_id'], ['screening_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predictions_image_id', 'ai_predictions', ['screening_image_id'], unique=False)
    op.create_index('idx_predictions_screening_id', 'ai_predictions', ['screening_id'], unique=False)
    op.create_index('idx_predictions_model_id', 'ai_predictions', ['ai_model_id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('dentist_id', sa.UUID(), nullable=False),
    sa.Column('stream_call_id', sa.String(length=128), nullable=False),
    sa.Column('stream_channel_id', sa.String(length=128), nullable=True),
    sa.Column('consultation_type', sa.String(length=30), nullable=False),
    sa.Column('session_status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("consultation_type IN ('video', 'audio', 'chat')", name='chk_consultation_type'),
    sa.CheckConstraint("session_status IN ('scheduled', 'active', 'ended', 'failed')", name='chk_session_status'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentists.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id'),
    sa.UniqueConstraint('stream_call_id')
    )
    op.create_index('idx_consultations_call_id', 'consultations', ['stream_call_id'], unique=True)
    op.create_index('idx_consultations_appointment', 'consultations', ['appointment_id'], unique=True)
    op.create_table('yolo_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screening_id', sa.UUID(), nullable=False),
    sa.Column('screening_image_id', sa.UUID(), nullable=False),
    sa.Column('ai_model_id', sa.UUID(), nullable=False),
    sa.Column('detected_class', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('bbox_x_min', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('bbox_y_min', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('bbox_x_max', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('bbox_y_max', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('detection_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bbox_x_max >= 0.0 AND bbox_x_max <= 1.0', name='chk_bbox_x_max'),
    sa.CheckConstraint('bbox_x_min >= 0.0 AND bbox_x_min <= 1.0', name='chk_bbox_x_min'),
    sa.CheckConstraint('bbox_y_max >= 0.0 AND bbox_y_max <= 1.0', name='chk_bbox_y_max'),
    sa.CheckConstraint('bbox_y_min >= 0.0 AND bbox_y_min <= 1.0', name='chk_bbox_y_min'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='chk_yolo_confidence'),
    sa.ForeignKeyConstraint(['ai_model_id'], ['ai_models.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screening_image_id'], ['screening_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_yolo_image_id', 'yolo_detections', ['screening_image_id'], unique=False)
    op.create_index('idx_yolo_screening_id', 'yolo_detections', ['screening_id'], unique=False)
    op.create_table('prediction_probabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_prediction_id', sa.UUID(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('class_index', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('probability >= 0.0 AND probability <= 1.0', name='chk_prob_range'),
    sa.ForeignKeyConstraint(['ai_prediction_id'], ['ai_predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_prediction_id', 'class_name', name='uq_prediction_class')
    )
    op.create_index('idx_pred_prob_prediction_id', 'prediction_probabilities', ['ai_prediction_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('screening_id', sa.UUID(), nullable=False),
    sa.Column('ai_prediction_id', sa.UUID(), nullable=True),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('low', 'moderate', 'high', 'critical')", name='chk_risk_level'),
    sa.CheckConstraint('risk_score >= 0.0 AND risk_score <= 100.0', name='chk_risk_score'),
    sa.ForeignKeyConstraint(['ai_prediction_id'], ['ai_predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_id')
    )
    op.create_index('idx_risk_level', 'risk_assessments', ['risk_level'], unique=False)
    op.create_index('idx_risk_screening_id', 'risk_assessments', ['screening_id'], unique=True)
    op.create_index(op.f('ix_risk_assessments_risk_level'), 'risk_assessments', ['risk_level'], unique=False)
    op.create_table('xai_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_prediction_id', sa.UUID(), nullable=False),
    sa.Column('screening_image_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('target_layer', sa.String(length=100), nullable=True),
    sa.Column('is_primary_user_facing', sa.Boolean(), nullable=False),
    sa.Column('heatmap_storage_path', sa.Text(), nullable=False),
    sa.Column('overlay_image_storage_path', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('grad_cam', 'occlusion_sensitivity', 'score_cam', 'grad_cam_plus_plus', 'layer_cam', 'integrated_gradients')", name='chk_xai_method'),
    sa.ForeignKeyConstraint(['ai_prediction_id'], ['ai_predictions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screening_image_id'], ['screening_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_xai_primary', 'xai_results', ['ai_prediction_id', 'is_primary_user_facing'], unique=False)
    op.create_index('idx_xai_prediction_id', 'xai_results', ['ai_prediction_id'], unique=False)
    op.create_index(op.f('ix_xai_results_method'), 'xai_results', ['method'], unique=False)
    op.create_index('idx_xai_method', 'xai_results', ['method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_xai_primary', table_name='xai_results')
    op.drop_index('idx_xai_prediction_id', table_name='xai_results')
    op.drop_index(op.f('ix_xai_results_method'), table_name='xai_results')
    op.drop_index('idx_xai_method', table_name='xai_results')
    op.drop_table('xai_results')
    op.drop_index('idx_risk_level', table_name='risk_assessments')
    op.drop_index('idx_risk_screening_id', table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_level'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('idx_pred_prob_prediction_id', table_name='prediction_probabilities')
    op.drop_table('prediction_probabilities')
    op.drop_index('idx_yolo_image_id', table_name='yolo_detections')
    op.drop_index('idx_yolo_screening_id', table_name='yolo_detections')
    op.drop_table('yolo_detections')
    op.drop_index('idx_consultations_call_id', table_name='consultations')
    op.drop_index('idx_consultations_appointment', table_name='consultations')
    op.drop_table('consultations')
    op.drop_index('idx_predictions_image_id', table_name='ai_predictions')
    op.drop_index('idx_predictions_screening_id', table_name='ai_predictions')
    op.drop_index('idx_predictions_model_id', table_name='ai_predictions')
    op.drop_table('ai_predictions')
    op.drop_index('idx_screening_images_screening_id', table_name='screening_images')
    op.drop_table('screening_images')
    op.drop_index('idx_reports_screening_id', table_name='reports')
    op.drop_index('idx_reports_number', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_dentist_assessments_dentist', table_name='dentist_assessments')
    op.drop_index('idx_dentist_assessments_screening', table_name='dentist_assessments')
    op.drop_table('dentist_assessments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index('idx_appts_dentist', table_name='appointments')
    op.drop_index('idx_appts_status', table_name='appointments')
    op.drop_index('idx_appts_patient', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('idx_screenings_patient_id', table_name='screenings')
    op.drop_index('idx_screenings_status', table_name='screenings')
    op.drop_index('idx_screenings_active', table_name='screenings')
    op.drop_index(op.f('ix_screenings_status'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_index('idx_medical_profiles_patient_id', table_name='patient_medical_profiles')
    op.drop_table('patient_medical_profiles')
    op.drop_index(op.f('ix_patient_dentist_relationships_status'), table_name='patient_dentist_relationships')
    op.drop_index('idx_pdr_patient_id', table_name='patient_dentist_relationships')
    op.drop_index('idx_pdr_status', table_name='patient_dentist_relationships')
    op.drop_index('idx_pdr_dentist_id', table_name='patient_dentist_relationships')
    op.drop_table('patient_dentist_relationships')
    op.drop_index('idx_dentist_verifications_status', table_name='dentist_verifications')
    op.drop_index('idx_dentist_verifications_dentist_id', table_name='dentist_verifications')
    op.drop_index(op.f('ix_dentist_verifications_status'), table_name='dentist_verifications')
    op.drop_table('dentist_verifications')
    op.drop_index('idx_availability_dentist', table_name='dentist_availabilities')
    op.drop_table('dentist_availabilities')
    op.drop_index('idx_conv_patient', table_name='conversations')
    op.drop_index('idx_conv_stream_channel', table_name='conversations')
    op.drop_index('idx_conv_dentist', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_patients_user_id', table_name='patients')
    op.drop_table('patients')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_dentists_user_id', table_name='dentists')
    op.drop_index('idx_dentists_verification_status', table_name='dentists')
    op.drop_index('idx_dentists_license', table_name='dentists')
    op.drop_index(op.f('ix_dentists_verification_status'), table_name='dentists')
    op.drop_table('dentists')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_firebase_uid', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_ai_models_active', table_name='ai_models')
    op.drop_table('ai_models')
    # ### end Alembic commands ###
