import puppeteer from 'file:///D:/npm-cache/_npx/702923228c2ce1e6/node_modules/puppeteer-core/lib/puppeteer/puppeteer-core.js';
import fs from 'node:fs';
import path from 'node:path';
const out=path.resolve('brag-output/composition/assets');
const browser=await puppeteer.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-dev-shm-usage']});
const page=await browser.newPage();
await page.setViewport({width:1440,height:1040,deviceScaleFactor:2});
page.on('pageerror',e=>console.error('PAGE ERROR',e.message));
const settle=async()=>{await page.evaluate(()=>document.fonts.ready);await new Promise(r=>setTimeout(r,500));};
const snap=async(name,selector)=>{await settle();if(selector){const e=await page.$(selector);if(!e)throw Error('Missing '+selector);await e.screenshot({path:path.join(out,name+'.png')});}else await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});console.log('Captured',name);};
const card=async(name,heading)=>{await settle();const el=await page.evaluateHandle(heading=>{const h=[...document.querySelectorAll('h1,h2,h3,h4')].find(e=>e.textContent.trim()===heading);if(!h)return null;let p=h.parentElement;while(p&&!(/rounded/.test(p.className)&&/border/.test(p.className)))p=p.parentElement;return p;},heading);if(!el.asElement())throw Error('Missing card '+heading);await el.asElement().screenshot({path:path.join(out,name+'.png')});console.log('Captured card',name);};
const clickText=async(text)=>{const found=await page.evaluate(text=>[...document.querySelectorAll('button,a')].filter(e=>e.textContent.trim()===text).map(e=>({tag:e.tagName,text:e.textContent.trim()})),text);if(found.length!==1)throw Error('Expected one '+text+' got '+found.length);await page.locator('::-p-text('+text+')').click();await settle();};
await page.goto('http://127.0.0.1:5173/patient/dashboard',{waitUntil:'networkidle0'});
await page.waitForSelector('main');
await snap('patient-dashboard');
console.log((await page.locator('body').waitHandle()).asElement() ? 'Patient UI ready':'');
if(process.argv.includes('--probe')){await browser.close();process.exit(0);}
await page.goto('http://127.0.0.1:5173/patient/screenings/new',{waitUntil:'networkidle0'});
await page.waitForSelector('#clinical-notes');
await page.type('#clinical-notes','Mild painless mucosal swelling on lower left lip for 2 weeks.',{delay:12});
await snap('patient-notes');
await clickText('Proceed to Image Selection');
await snap('upload-empty');
const input=await page.$('input[type=file]');await input.uploadFile(path.resolve('brag-output/images/Mucocele.png'));
await snap('upload-preview');
await clickText('Upload & Run AI Analysis');
await page.waitForFunction(()=>document.body.innerText.includes('Analyzing Oral Photograph'));
await snap('analysis-loading');
await page.waitForFunction(()=>document.body.innerText.includes('Screening Session Results'));
await settle();await snap('patient-results');
console.log('RESULT HEADINGS',await page.evaluate(()=>[...document.querySelectorAll('h1,h2,h3,h4')].map(e=>e.textContent.trim())));
await page.evaluate(()=>document.querySelector('h3')?.scrollIntoView());
await snap('results-viewport');
await clickText('Request Dentist Review');
await snap('request-review');
console.log('MODAL BUTTONS',await page.evaluate(()=>[...document.querySelectorAll('[role=dialog] button')].map(e=>e.textContent.trim())));
await snap('review-modal','[role=dialog]');
await clickText('Send Request');
await new Promise(r=>setTimeout(r,1700));
await snap('review-requested');
await page.goto('http://127.0.0.1:5173/dentist/dashboard',{waitUntil:'networkidle0'});
await snap('dentist-dashboard');
await page.goto('http://127.0.0.1:5173/dentist/screenings/550e8400-e29b-41d4-a716-446655440000/review',{waitUntil:'networkidle0'});
await page.waitForSelector('#clinical_observations');
await snap('dentist-review');
console.log('DENTIST HEADINGS',await page.evaluate(()=>[...document.querySelectorAll('h1,h2,h3,h4')].map(e=>e.textContent.trim())));
await page.type('#clinical_observations','Synthetic demonstration: circumscribed mucosal swelling; oral image and AI evidence reviewed.',{delay:8});
await page.type('#diagnosis_notes','Preliminary assessment documented separately from AI output. In-person examination required for confirmation.',{delay:8});
await page.type('#treatment_recommendation','Arrange an in-person dental review. Follow-up and any referral depend on the clinical examination.',{delay:8});
await card('dentist-assessment','Professional Clinical Assessment');
await clickText('Save Draft');
await clickText('Finalize Assessment');
await snap('finalize-confirmation','[role=dialog]');
await clickText('Confirm Finalization');
await settle();
await card('dentist-finalized','Professional Clinical Assessment');
await clickText('Generate Clinical Report (PDF)');
await page.waitForFunction(()=>document.body.innerText.includes('Report Available'));
await card('report-card','Clinical Report (PDF)');
await clickText('Download Clinical Report (PDF)');
await page.goto('http://127.0.0.1:5173/patient/screenings/550e8400-e29b-41d4-a716-446655440000',{waitUntil:'networkidle0'});
await snap('patient-reviewed');
await card('patient-assessment','Dentist Clinical Assessment');
await browser.close();
